version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: book-todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: book_todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d book_todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
#   # Optional: pgAdmin for database management
#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: book-todo-pgadmin
#     restart: unless-stopped
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: admin123
#       PGADMIN_CONFIG_SERVER_MODE: 'False'
#     ports:
#       - "8080:80"
#     volumes:
#       - pgadmin_data:/var/lib/pgadmin
#     depends_on:
#       postgres:
#         condition: service_healthy

# volumes:
#   postgres_data:
#   pgadmin_data:
