version: "3.8"

services:
  app:
    image: 568150/book-todo-app:prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book_todo_db_doc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
# To run migrations, you can use the following command:
#run this command after starting the containers
#docker-compose exec app npx prisma migrate deploy
