version: "3.9"

services:
  book-todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app # Bind mount source code for live reload
      - /app/node_modules # Prevent overwrite of node_modules by bind mount
    command: sh -c "yarn prisma migrate deploy && yarn dev"
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book_todo_db_doc
    volumes:
      - /Users/nahidkaiser/NK/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
